# we need trusty for the chrome addon
dist: trusty

sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - 8
  - 9

before_script:
  - yarn global add @angular/cli

script:
  - yarn run build:ssr
  - yarn run e2e
  - yarn run test
